import { useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import '../styles/notfound.css'

/* PAINT:BEGIN -- generated by site/paint/generate.py; do not hand-edit */
const PAINT = { w: 432, h: 27, bits: "AAAAAHwAAAAAAAAAAAAAAAAAH4AAAAAAAAAAAAAA/AAAAAAAAAAAAAA/AAAAAAAAAAAAAAAAAD/AA/+AAB/gAAH//AAP8AAB//gD//4AAD+AH4AH/4A///+AAH//4AH/4AH4A/gf4A/Af/4AAD/AB//AAD/gAAH//4AP+AAH//4D//4AAD/AH4Af/+A///+AAH//4Af/+AH4A/gf4A/Af//AAH/AD//gAD/gAAH//8Af+AAP//4D//4AAD/AH4A///A///+AAH//4A///AH4A/gf8A/Af//gAP/AH//gAH/gAAH//+Af+AAf//4D//4AAD/gH4B///g///+AAH//4B///gH4A/gf8A/Af//4AP/AH8fwAP/gAAH//+A/+AA/8H4D//4AAD/wH4D/j/w///+AAH//4D/j/wH4A/gf+A/Af//8Af/AP4P4AP/gAAH8D/A//AB/wA4D8AAAAD/wH4H+A/wAP4AAAH8AAH+A/wH4A/gf+A/Afg/8A+/APwH4Af/gAAH8B/A//AB/AAAD8AAAAD/4H4H8AP4AP4AAAH8AAH8AP4H4A/gf/A/AfgH+A+/AfwH4A+/gAAH8B/B+fgD+AAAD8AAAAD/4H4H4AP4AP4AAAH8AAP4AP4H4A/gf/g/AfgD/B8/AfwH8A+/gAAH8B/B+fgD+AAAD8AAAAD/8H4P4AH4AP4AAAH8AAP4AP4H4A/gfvg/AfgB/B4/AfwH8B8/gAAH8B/B+fgD+AAAD8AAAAD98H4P4AH8AP4AAAH8AAP4AH8H4A/gfvg/AfgB/Dw/AfgH8B4/gAAH8B/D+PwD+AAAD//4AAD9+H4P4AH8AP4AAAH//wP4AH8H4A/gfnw/AfgA/Hw/AfgH8Dw/gAAH8D/D8PwD8AAAD//4AAD8+H4P4AH8AP4AAAH//wPwAH8H4A/gfnw/AfgA/Pg/AfgH8Hw/gAAH//+D8P4D8B/8D//4AAD8/H4P4AH8AP4AAAH//wPwAH8H4A/gfj4/AfgA/PA/AfgH8Pg/gAAH//+H8H4D8B/8D//4AAD8fH4P4AH8AP4AAAH//wPwAH8H4A/gfj8/AfgA/fA/AfgH8PA/gAAH//8H4H4D8B/8D//4AAD8Pn4P4AH8AP4AAAH//wPwAH8H4A/gfh8/AfgA/+A/AfwH8fA/gAAH//4P4H8D+B/8D8AAAAD8Pn4P4AH8AP4AAAH8AAP4AH8H4A/gfh+/AfgA////8fwH8f//8AAH//AP//8D+AD8D8AAAAD8H34P4AH8AP4AAAH8AAP4AH8H4A/gfg+/AfgB////8fwH8f//8AAH8AAP//+D+AD8D8AAAAD8H/4P4AH4AP4AAAH8AAP4AP4H4A/gfg//AfgB////8fwH4f//8AAH8AAf//+D+AD8D8AAAAD8D/4H4AP4AP4AAAH8AAP4AP4H8A/gfgf/AfgD////8PwH4f//8AAH8AAf//+B/AD8D8AAAAD8D/4H8AP4AP4AAAH8AAH8AP4H8A/gfgf/AfgH+///8P4P4f//8AAH8AAf//+B/wD8D8AAAAD8B/4H+A/wAP4AAAH8AAH+A/wD+B/AfgP/Afh/8AA/AH8fwAA/gAAH8AA/gB/A/8P8D//8AAD8B/4D/z/wAP4AAAH8AAD/z/wD///AfgP/Af//8AA/AH//gAA/gAAH8AA/AA/Af//8D//8AAD8A/4B///gAP4AAAH8AAB///gB//+AfgH/Af//4AA/AD//gAA/gAAH8AB/AA/gP//8D//8AAD8A/4A///AAP4AAAH8AAA///AB//8AfgH/Af//gAA/AB//AAA/gAAH8AB/AA/gH//4D//8AAD8Af4Af/+AAP4AAAH8AAAf/+AA//4AfgD/Af//AAA/AA/8AAA/gAAH8AB+AAfgB//AD//8AAD8Af4AH/4AAP4AAAH8AAAH/4AAP/gAfgB/Af/wA" };
/* PAINT:END */

const NBINS = 512 // frequency bins across the display
const ROWS = 336 // time rows held on screen
const FRAME_MS = 50 // one waterfall row per 50 ms
const PAINT_REPEAT = 3 // hold each bitmap row this many rows -- real paint is slow
const FIRST_PAINT_MS = 11000
const PAINT_GAP_MS = 24000
const PAINT_POWER = 26 // ~14 dB over the noise floor
const SPAN_DB = 26

const paintRows = PAINT.h * PAINT_REPEAT
const gapRows = Math.round(PAINT_GAP_MS / FRAME_MS)
const firstRows = Math.round(FIRST_PAINT_MS / FRAME_MS)
const cycleRows = paintRows + gapRows
const originX = (NBINS - PAINT.w) >> 1

const LUT = (() => {
  const stops: [number, [number, number, number]][] = [
    [0.0, [4, 6, 16]], [0.16, [12, 24, 74]], [0.34, [20, 72, 152]],
    [0.5, [24, 140, 152]], [0.64, [44, 176, 88]], [0.77, [190, 200, 52]],
    [0.88, [240, 152, 42]], [0.96, [246, 82, 50]], [1.0, [255, 240, 222]],
  ]
  const lut = new Uint8Array(256 * 3)
  for (let i = 0; i < 256; i++) {
    const t = i / 255
    let a = stops[0]
    let b = stops[stops.length - 1]
    for (let s = 0; s < stops.length - 1; s++) {
      if (t >= stops[s][0] && t <= stops[s + 1][0]) {
        a = stops[s]
        b = stops[s + 1]
        break
      }
    }
    const f = (t - a[0]) / (b[0] - a[0] || 1)
    for (let c = 0; c < 3; c++) lut[i * 3 + c] = Math.round(a[1][c] + (b[1][c] - a[1][c]) * f)
  }
  return lut
})()

// Hashed noise, not Math.random: every row is a pure function of its step, so
// re-rendering at a new gain reproduces the same scene instead of reshuffling it.
function urand(step: number, bin: number): number {
  let x = Math.imul(step + 1, 374761393) ^ Math.imul(bin + 1, 668265263)
  x = Math.imul(x ^ (x >>> 13), 1274126177)
  x ^= x >>> 16
  return ((x >>> 0) + 0.5) / 4294967296
}

function passband(i: number): number {
  const x = (i / (NBINS - 1)) * 2 - 1
  return 0.35 + 0.65 * Math.pow(Math.cos(x * 1.35), 2)
}

function addBump(buf: Float32Array, center: number, width: number, power: number): void {
  const lo = Math.max(0, Math.floor(center - width * 3))
  const hi = Math.min(NBINS - 1, Math.ceil(center + width * 3))
  for (let i = lo; i <= hi; i++) {
    const d = (i - center) / width
    buf[i] += power * Math.exp(-0.5 * d * d)
  }
}

const HOPS = [212, 236, 258, 274, 290, 222, 246, 266]

function addSignals(buf: Float32Array, step: number): void {
  const t = (step * FRAME_MS) / 1000
  addBump(buf, 88, 1.1, 55 * (0.9 + 0.2 * Math.sin(t * 3.1))) // CW carrier
  addBump(buf, 168 + 34 * Math.sin(t * 0.11), 2.2, 22) // slow drifter
  addBump(buf, Math.floor(step / 5) % 2 === 0 ? 306 : 318, 1.6, 34) // FSK pair
  addBump(buf, 430, 16, 3.5 * (0.85 + 0.3 * Math.sin(t * 0.7))) // wideband hump
  if (step % 11 < 6) addBump(buf, HOPS[(step * 5 + 3) % HOPS.length], 1.8, 26)
}

export default function NotFound() {
  const canvasRef = useRef<HTMLCanvasElement>(null)
  const floorRef = useRef(-4) // matches the gain slider's default of 50
  const redrawRef = useRef<(() => void) | null>(null)
  const [gain, setGain] = useState(50)

  useEffect(() => {
    const view = canvasRef.current
    if (!view) return
    const vctx = view.getContext('2d', { alpha: false })
    if (!vctx) return

    const bytes = Uint8Array.from(atob(PAINT.bits || ''), (c) => c.charCodeAt(0))

    const wf = document.createElement('canvas')
    wf.width = NBINS
    wf.height = ROWS
    const wctx = wf.getContext('2d', { alpha: false })
    if (!wctx) return
    // The `!` below are load-bearing: TS does not carry the null guards above
    // into hoisted function declarations, only into arrow closures.
    const rowImg = wctx.createImageData(NBINS, 1)
    const power = new Float32Array(NBINS)

    function paintIndex(step: number): number {
      if (step < firstRows || !bytes.length) return -1
      const k = (step - firstRows) % cycleRows
      return k < paintRows ? Math.floor(k / PAINT_REPEAT) : -1
    }

    function addPaint(buf: Float32Array, step: number): void {
      const idx = paintIndex(step)
      if (idx < 0) return
      // New rows enter at the top, so emit the bitmap bottom-up to land upright.
      const base = (PAINT.h - 1 - idx) * PAINT.w
      for (let c = 0; c < PAINT.w; c++) {
        const bit = base + c
        if ((bytes[bit >> 3] >> (7 - (bit & 7))) & 1) buf[originX + c] += PAINT_POWER
      }
    }

    function renderRow(step: number, px: Uint8ClampedArray): void {
      for (let i = 0; i < NBINS; i++) power[i] = passband(i) * -Math.log(1 - urand(step, i))
      addSignals(power, step)
      addPaint(power, step)
      const floorDb = floorRef.current
      for (let i = 0; i < NBINS; i++) {
        let t = (10 * Math.log10(power[i] + 1e-6) - floorDb) / SPAN_DB
        t = t < 0 ? 0 : t > 1 ? 1 : t
        const k = ((t * 255) | 0) * 3
        px[i * 4] = LUT[k]
        px[i * 4 + 1] = LUT[k + 1]
        px[i * 4 + 2] = LUT[k + 2]
        px[i * 4 + 3] = 255
      }
    }

    function blit(): void {
      vctx!.imageSmoothingEnabled = true
      vctx!.imageSmoothingQuality = 'high'
      vctx!.drawImage(wf, 0, 0, view!.width, view!.height)
    }

    function pushRow(step: number): void {
      wctx!.drawImage(wf, 0, 0, NBINS, ROWS - 1, 0, 1, NBINS, ROWS - 1)
      renderRow(step, rowImg.data)
      wctx!.putImageData(rowImg, 0, 0)
    }

    // Fill the whole buffer as it would look at `endStep`: newest row on top.
    function fillFrom(endStep: number): void {
      for (let y = 0; y < ROWS; y++) {
        renderRow(endStep - 1 - y, rowImg.data)
        wctx!.putImageData(rowImg, 0, y)
      }
    }

    function resize(): void {
      const dpr = Math.min(window.devicePixelRatio || 1, 2)
      view!.width = Math.max(1, Math.round(window.innerWidth * dpr))
      view!.height = Math.max(1, Math.round(window.innerHeight * dpr))
      blit()
    }

    const still = window.matchMedia('(prefers-reduced-motion: reduce)')
    // Without animation nobody would ever see a pass, so freeze on one mid-screen.
    const stillStep = firstRows + (paintRows >> 1) + (ROWS >> 1) + 1

    let step = 0
    let carry = 0
    let prev = 0
    let raf = 0

    function frame(now: number): void {
      raf = requestAnimationFrame(frame)
      carry += now - prev
      prev = now
      if (carry > 400) carry = FRAME_MS // returning from a hidden tab: don't burst
      while (carry >= FRAME_MS) {
        carry -= FRAME_MS
        pushRow(step++)
      }
      blit()
    }

    function start(): void {
      cancelAnimationFrame(raf)
      if (still.matches) {
        fillFrom(stillStep)
        blit()
        return
      }
      fillFrom(0)
      step = 0
      carry = 0
      prev = performance.now()
      raf = requestAnimationFrame(frame)
    }

    // The panel is fixed and full-bleed; let the page behind it not scroll.
    const priorOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'

    redrawRef.current = () => {
      if (still.matches) {
        fillFrom(stillStep)
        blit()
      }
    }

    window.addEventListener('resize', resize)
    still.addEventListener('change', start)
    resize()
    start()

    return () => {
      cancelAnimationFrame(raf)
      window.removeEventListener('resize', resize)
      still.removeEventListener('change', start)
      document.body.style.overflow = priorOverflow
      redrawRef.current = null
    }
  }, [])

  return (
    <div className="nf">
      <canvas
        ref={canvasRef}
        className="nf-canvas"
        aria-label="Spectrum waterfall showing the 404 band"
      />

      <div className="nf-panel">
        <p className="nf-code">404</p>
        <p className="nf-sub">Signal not found</p>
        <p className="nf-body">
          Nothing is transmitting at this URL. The band is not empty.
        </p>
        <Link className="nf-home" to="/">
          ← home
        </Link>
      </div>

      <label className="nf-gain">
        GAIN
        <input
          type="range"
          min="0"
          max="100"
          value={gain}
          aria-label="Waterfall display gain"
          onChange={(e) => {
            const v = Number(e.target.value)
            setGain(v)
            floorRef.current = 4 - (v / 100) * 16
            redrawRef.current?.()
          }}
        />
      </label>
    </div>
  )
}
